sudo: true
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get install --yes snapd
  - sudo snap install lxd
  - sleep 30
  - sudo /snap/bin/lxd init --auto
  - sudo /snap/bin/lxc network create testbr0
  - sudo /snap/bin/lxc network attach-profile testbr0 default eth0
  - sudo /snap/bin/lxc launch --ephemeral ubuntu:xenial test-container

script:
  - sudo /snap/bin/lxc exec test-container -- apt-get update && apt-get install --yes snapd squashfuse
  - sudo /snap/bin/lxc exec test-container -- snap install hugo
  - sudo /snap/bin/lxc exec test-container -- hugo new site test-site
