sudo: true
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap install lxd
  - sudo /snap/bin/lxd init --auto
  - sudo /snap/bin/lxc launch ubuntu:xenial

script:
  - /snap/bin/hugo new site test-site
